# Generated by Django 6.1.1 on 2026-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX 3D'), ('4DX', '4DX')], default='2D', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(default='Hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='theatre',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theatre',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('RECLINER', 'Recliner')], max_length=20),
        ),
    ]
